// <auto-generated />
namespace Fever.Compoments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_MenuItem_CommandAction_userInfo_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_MenuItem_CommandAction_userInfo_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201708311346334_add_MenuItem_CommandAction_userInfo_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
