// <auto-generated />
namespace Fever.Compoments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Setup_AdminPlat_Core_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setup_AdminPlat_Core_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201708311555513_Setup_AdminPlat_Core_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
